config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'prototypes#index'
  resources :prototypes do
    resources :comments, only: :create
  end
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :prototype
  validates :comment, presence: true
end

app/models/prototype.rb
class Prototype < ApplicationRecord
  belongs_to :user
  has_one_attached :image
  validates :protoname, presence: true
  validates :catchcopy, presence: true
  validates :concept, presence: true
  validates :image, presence: true
  has_many :comments, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :username, :profile, :job, :position, presence: true
  has_many :prototypes
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :profile, :job, :position])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    if @comment.save
      redirect_to "/prototypes/#{@comment.prototype.id}"
    else
      @prototype = Prototype.find(params[:prototype_id])
      @comments = @prototype.comments.includes(:user)
      render 'prototypes/show', status: :unprocessable_entity

    end
  end

  private

  def comment_params
    params.require(:comment).permit(:comment).merge(user_id: current_user.id, prototype_id: params[:prototype_id])
  end
end

app/controllers/prototypes_controller.rb
class PrototypesController < ApplicationController
  before_action :set_prototype, only: :show
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :ensure_correct_user, only: :destroy

  def index
    @prototypes = Prototype.all
  end

  def new
    @prototype = Prototype.new
  end

  def create
    @prototype = Prototype.new(prototype_params)
    if @prototype.save
      redirect_to '/'
    else
      render '/prototypes/new', status: :unprocessable_entity
    end
  end

  def edit
    @prototype = Prototype.find(params[:id])
    return if current_user == @prototype.user

    redirect_to root_path
  end

  def update
    @prototype = Prototype.find(params[:id])
    if @prototype.update(prototype_params)
      redirect_to prototype_path(@prototype)
    else
      render :edit
    end
  end

  def show
    @comment = Comment.new
    @comments = @prototype.comments.includes(:user)
    @prototype = Prototype.find(params[:id])
  end

  def destroy
    prototype = Prototype.find(params[:id])
    prototype.destroy
    redirect_to root_path
  end

  private

  def set_prototype
    @prototype = Prototype.find(params[:id])
  end

  def prototype_params
    params.require(:prototype).permit(:protoname, :catchcopy, :concept, :image).merge(user_id: current_user.id)
  end

  def ensure_correct_user
    @prototype = Prototype.find(params[:id])
    return if current_user == @prototype.user

    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    user = User.all
  end

  def show
    @user = User.find(params[:id])
    @username = User.find(params[:id])
    @profile = User.find(params[:id])
    @job = User.find(params[:id])
    @prototypes = @user.prototypes
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/prototypes_helper.rb
module PrototypesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Protospace</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP:400,700,900&display=swap" rel="stylesheet">
  </head>

  <body>
    <header class="header">
      <div class="inner">
        <div class="nav">
          <div class="nav__left">
            <%= link_to image_tag("logo.png", class: :logo), root_path %>
          </div>
            <div class="nav__right">
            <% if user_signed_in? %>
              <%= link_to "ログアウト",  destroy_user_session_path, data: { turbo_method: :delete }, class: :nav__logout %>
              <%= link_to "New Proto", new_prototype_path, class: :nav__btn %>
            </div>
            <%# New Protoのパスを後で入力する %>
            <% else %>
            <div class="nav__right">
              <%= link_to "ログイン",  new_user_session_path, class: :nav__btn %>
              <%= link_to "新規登録", new_user_registration_path, class: :nav__btn %>
            </div>
            <% end%>
        </div>
      </div>
    </header>
    <%= yield %>
    <footer class="footer">
      <p class="copyright">Copyright © PROTO SPACE All rights reserved.</p>
    </footer>
  </body>
</html>

app/views/prototypes/_form.html.erb
<%= form_with model: @prototype, local: true do |f|%>
  <div class="field">
    <%= f.label :protoname, "プロトタイプの名称" %><br />
    <%= f.text_field :protoname, id:"prototype__title" %>
  </div>

  <div class="field">
    <%= f.label :catchcopy, "キャッチコピー" %><br />
    <%= f.text_area :catchcopy, class: :form_text, id:"prototype_catch_copy" %>
  </div>

  <div class="field">
    <%= f.label :concept, "コンセプト" %><br />
    <%= f.text_area :concept, class: :form_text, id:"prototype_concept" %>
  </div>

  <div class="field">
    <%= f.label :image, "プロトタイプの画像" %><br />
    <%= f.file_field :image, id:"prototype_image" %>
  </div>
   
  <div class="actions">
    <%= f.submit "保存する", class: :form_btn  %>
  </div>
<% end %>

app/views/prototypes/_prototype.html.erb
<div class="card">
  <%= link_to image_tag(prototype.image, class: :card__img), prototype_path(prototype.id) %>
  <div class="card__body">
    <%= link_to prototype.protoname, prototype_path(prototype.id) ,class: :card__title%>
    <p class="card__summary">
      <%= prototype.catchcopy %>
    </p>
    <%= link_to "by #{prototype.user.username}", user_path(prototype.user), class: :card__user %>
  </div>
</div>

app/views/prototypes/edit.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">プロトタイプ編集</h2>
       <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/index.html.erb
<main class="main">
  <div class="inner">
    <div class="greeting">
      <% if user_signed_in? %>  
        こんにちは、
        <%= link_to "#{current_user.username}さん", user_path(current_user), class: :greeting__link %>
      <% end %>
    </div>
    <div class="card__wrapper">
      <% @prototypes.each do |prototype| %>
        <%= render partial: "prototype", locals: { prototype: prototype } %>
      <% end %>
    </div>
  </div>
</main>

app/views/prototypes/new.html.erb
<div class="main">
  <div class="inner">
    <div class="form__wrapper">
      <h2 class="page-heading">新規プロトタイプ投稿</h2>
           <%= render partial: "form", locals: { prototype: @prototype } %>
    </div>
  </div>
</div>

app/views/prototypes/show.html.erb
<main class="main">
  <div class="inner">
    <div class="prototype__wrapper">
      <p class="prototype__hedding">
        <%= @prototype.protoname %>
      </p>
      <%= link_to "by #{@prototype.user.username}", user_path(@prototype.user), class: :prototype__user %>
     <% if user_signed_in? && current_user.id == @prototype.user_id %>
        <div class="prototype__manage">
          <%= link_to "編集する", edit_prototype_path, class: :prototype__btn %>
          <%= link_to "削除する", prototype_path(@prototype.id), data: { turbo_method: :delete }, class: :prototype__btn %>
        </div>
    <% end %>
      <div class="prototype__image">
        <%= image_tag @prototype.image  %>
      </div>
      <div class="prototype__body">
        <div class="prototype__detail">
          <p class="detail__title">キャッチコピー</p>
          <p class="detail__message">
            <%= @prototype.catchcopy  %>
          </p>
        </div>
        <div class="prototype__detail">
          <p class="detail__title">コンセプト</p>
          <p class="detail__message">
            <%= @prototype.concept %>
          </p>
        </div>
      </div>
      <div class="prototype__comments">
         <% if user_signed_in? %>
          <%= form_with(model:[@prototype,@comment],local: true) do |f|%>
            <div class="field">
              <%= f.label :comment, "コメント" %><br />
              <%= f.text_field :comment, id:"comment_content" %>
            </div>
            <div class="actions">
            <%= f.submit "送信する", class: :form__btn %>
            </div>
          <% end %>
         <% end %>
        <ul class="comments_lists">
          <% @comments.each do |comment|%>
            <li class="comments_list">
              <%= comment.comment%>
              <%= link_to "（#{comment.user.username}）", user_path(comment.user), class: :comment_user %>
            </li>
          <%end%>
        </ul>
      </div>
    </div>
  </div>
</main>

app/views/users/show.html.erb
<div class="main">
  <div class="inner">
    <div class="user__wrapper">
      <h2 class="page-heading">
        <%= "#{@user.username}さんの情報"%>
      </h2>
      <table class="table">
        <tbody>
          <tr>
            <th class="table__col1">名前</th>
            <td class="table__col2"><%= "#{@user.username}" %></td>
          </tr>
          <tr>
            <th class="table__col1">プロフィール</th>
            <td class="table__col2"><%= "#{@user.profile}" %></td>
          </tr>
          <tr>
            <th class="table__col1">所属</th>
            <td class="table__col2"><%= "#{@user.job}" %></td>
          </tr>
          <tr>
            <th class="table__col1">役職</th>
            <td class="table__col2"><%= "#{@user.position}" %></td>
          </tr>
        </tbody>
      </table>
      <h2 class="page-heading">
        <%= "#{@user.username}さんのプロトタイプ"%>
      </h2>
      <div class="user__card">
        <% @prototypes.each do |prototype| %>
          <%= render partial: "prototypes/prototype", locals: { prototype: prototype } %>
        <% end %>
      </div>
    </div>
  </div>
</div>